version: "3"
name: sonarqube
services:
  init:
    image: bash
    privileged: true
    user: root
    volumes:
      - $PWD/scripts/init.sh:/mnt/init.sh
    command: ["sh", "-e", "/mnt/init.sh"]

  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      TZ: Europe/Madrid
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf
      - ./conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072
    ports:
      - "9000:9000"
    networks:
      - network
  db:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    environment:
      TZ: Europe/Madrid
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_conf:
  postgresql:
  postgresql_data:
