version: '2'

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    container_name: openldap
    hostname: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ENABLE_TLS=no
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      - network

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    link:
      openldap: ldap-host
    environment:
      # bitnami/openldap uses non-privileged port as default
      #PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'192.168.1.8': [{'server': [{ 'port': 1389 }]}]}]"
      PHPLDAPADMIN_LDAP_HOSTS: ldap-host
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "false"
    networks:
      - network
    ports:
      - "8080:80"
    depends_on:
      - openldap

networks:
  network:
    driver: bridge

volumes:
  openldap_data:
    driver: local
