version: '2'
name: ldap-service
services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    container_name: openldap
    hostname: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      # Default LDAP_ROOT: dc=example,dc=org
      - LDAP_ROOT=dc=protossnet,dc=local
      - LDAP_ADMIN_PASSWORD_FILE=/run/secrets/ldap_admin_password
      #- LDAP_USERS=user01,user02
      #- LDAP_PASSWORDS=password1,password2
      - LDAP_ENABLE_TLS=no
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      - network
    secrets:
      - ldap_admin_password

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    # Don't know why this link attribute started to fail
    #link:
    #  openldap: ldap-server
    environment:
      # bitnami/openldap uses non-privileged port as default
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{ 'port': 1389 }]}]}]"
      #PHPLDAPADMIN_LDAP_HOSTS: ldap-host
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "false"
    networks:
      - network
    ports:
      - "8080:80"
    depends_on:
      - openldap

networks:
  network:
    driver: bridge

volumes:
  openldap_data:
    driver: local

secrets:
  ldap_admin_password:
    file: secrets/ldap_admin_password.txt
