FROM nginx:alpine
MAINTAINER ProtossGP32 <19353116+ProtossGP32@users.noreply.github.com>

# Copy the Nginx config file
#RUN rm /etc/nginx/conf.d/default.conf
#COPY configs/nginx/nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80

# Copy the website files
COPY website /usr/share/nginx/html/
